# Generated by Django 5.2.4 on 2025-08-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Write a short bio')),
                ('avatar', models.ImageField(blank=True, help_text='Profile avatar image (optional)', null=True, upload_to='')),
                ('badges', models.ManyToManyField(blank=True, help_text='Badges awarded to this user', related_name='users', to='badges.badge')),
                ('user', models.OneToOneField(help_text='Related user for this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
