# Generated by Django 5.2.4 on 2025-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='Badges awarded to this user', related_name='users', to='badges.badge'),
        ),
    ]
