# Generated by Django 5.2.4 on 2025-08-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitialSetup',
        ),
    ]
