# Generated by Django 5.2.4 on 2025-08-02 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initialsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile avatar image (optional)', max_length=255, null=True),
        ),
    ]
