# Generated by Django 5.2.4 on 2025-08-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Question headline.', max_length=150)),
                ('body', models.TextField(help_text='Detailed question description.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Update timestamp.')),
                ('author', models.ForeignKey(help_text='User who asked the question.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for topic categorization.', related_name='questions', to='tags.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
