# Generated by Django 5.2.4 on 2025-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='media',
            field=models.ImageField(blank=True, help_text='Optional image for context.', null=True, upload_to=''),
        ),
    ]
