# Generated by Django 5.2.4 on 2025-08-05 12:58

import DjangoQandAPlatform.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_answer_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='media',
            field=models.ImageField(blank=True, help_text='Optional image for context.', null=True, upload_to='', validators=[DjangoQandAPlatform.validators.SizeValidator(10)]),
        ),
    ]
