# Generated by Django 5.2.4 on 2025-08-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related Question, Answer, or Comment.')),
                ('author', models.ForeignKey(help_text='User who authored the comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='Type: Question, Answer, or Comment referenced.', limit_choices_to=models.Q(models.Q(('app_label', 'questions'), ('model', 'question')), models.Q(('app_label', 'answers'), ('model', 'answer')), models.Q(('app_label', 'comments'), ('model', 'comment')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
