# Generated by Django 5.2.4 on 2025-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related Question, Answer, or Comment.')),
            ],
        ),
    ]
