# Generated by Django 5.2.4 on 2025-08-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_author_alter_comment_content_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(help_text='Type: Question, Answer, or Comment referenced.', limit_choices_to=models.Q(models.Q(('app_label', 'questions'), ('model', 'question')), models.Q(('app_label', 'answers'), ('model', 'answer')), models.Q(('app_label', 'comments'), ('model', 'comment')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID of the related Question, Answer, or Comment.'),
        ),
    ]
