# Generated by Django 5.2.4 on 2025-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique human-readable tag name (e.g. 'python').", max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Always auto-generated from name', max_length=40)),
            ],
        ),
    ]
