# Generated by Django 5.2.4 on 2025-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Always auto-generated from name', max_length=40),
        ),
    ]
