# Generated by Django 5.2.4 on 2025-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_created', models.BooleanField(default=False)),
            ],
        ),
    ]
