# Generated by Django 5.2.4 on 2025-07-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique badge name, e.g., 'Top Answerer'", max_length=50, unique=True)),
                ('description', models.TextField(help_text='What this badge is awarded for')),
                ('icon', models.ImageField(blank=True, help_text='Optional badge icon image', null=True, upload_to='badges/')),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
            ],
        ),
    ]
