# Generated by Django 5.2.4 on 2025-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.SlugField(blank=True, help_text='Always auto-generated from name', max_length=40, unique=True),
        ),
    ]
