# Generated by Django 5.2.4 on 2025-08-02 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_badge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional badge icon image', max_length=255, null=True),
        ),
    ]
