# Generated by Django 5.2.4 on 2025-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional badge icon image', null=True, upload_to=''),
        ),
    ]
